// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTunnel creates a new instance of MockTunnel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTunnel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTunnel {
	mock := &MockTunnel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTunnel is an autogenerated mock type for the Tunnel type
type MockTunnel struct {
	mock.Mock
}

type MockTunnel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTunnel) EXPECT() *MockTunnel_Expecter {
	return &MockTunnel_Expecter{mock: &_m.Mock}
}

// MissingTokenError provides a mock function for the type MockTunnel
func (_mock *MockTunnel) MissingTokenError() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MissingTokenError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnel_MissingTokenError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MissingTokenError'
type MockTunnel_MissingTokenError_Call struct {
	*mock.Call
}

// MissingTokenError is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) MissingTokenError() *MockTunnel_MissingTokenError_Call {
	return &MockTunnel_MissingTokenError_Call{Call: _e.mock.On("MissingTokenError")}
}

func (_c *MockTunnel_MissingTokenError_Call) Run(run func()) *MockTunnel_MissingTokenError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_MissingTokenError_Call) Return(err error) *MockTunnel_MissingTokenError_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnel_MissingTokenError_Call) RunAndReturn(run func() error) *MockTunnel_MissingTokenError_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTunnel_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTunnel_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Name() *MockTunnel_Name_Call {
	return &MockTunnel_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTunnel_Name_Call) Run(run func()) *MockTunnel_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Name_Call) Return(s string) *MockTunnel_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTunnel_Name_Call) RunAndReturn(run func() string) *MockTunnel_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OAuthBaseURL provides a mock function for the type MockTunnel
func (_mock *MockTunnel) OAuthBaseURL(explicitURL string, tunnelURL string) (string, error) {
	ret := _mock.Called(explicitURL, tunnelURL)

	if len(ret) == 0 {
		panic("no return value specified for OAuthBaseURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(explicitURL, tunnelURL)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(explicitURL, tunnelURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(explicitURL, tunnelURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnel_OAuthBaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OAuthBaseURL'
type MockTunnel_OAuthBaseURL_Call struct {
	*mock.Call
}

// OAuthBaseURL is a helper method to define mock.On call
//   - explicitURL string
//   - tunnelURL string
func (_e *MockTunnel_Expecter) OAuthBaseURL(explicitURL any, tunnelURL any) *MockTunnel_OAuthBaseURL_Call {
	return &MockTunnel_OAuthBaseURL_Call{Call: _e.mock.On("OAuthBaseURL", explicitURL, tunnelURL)}
}

func (_c *MockTunnel_OAuthBaseURL_Call) Run(run func(explicitURL string, tunnelURL string)) *MockTunnel_OAuthBaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnel_OAuthBaseURL_Call) Return(s string, err error) *MockTunnel_OAuthBaseURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTunnel_OAuthBaseURL_Call) RunAndReturn(run func(explicitURL string, tunnelURL string) (string, error)) *MockTunnel_OAuthBaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// RequiresToken provides a mock function for the type MockTunnel
func (_mock *MockTunnel) RequiresToken() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequiresToken")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTunnel_RequiresToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequiresToken'
type MockTunnel_RequiresToken_Call struct {
	*mock.Call
}

// RequiresToken is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) RequiresToken() *MockTunnel_RequiresToken_Call {
	return &MockTunnel_RequiresToken_Call{Call: _e.mock.On("RequiresToken")}
}

func (_c *MockTunnel_RequiresToken_Call) Run(run func()) *MockTunnel_RequiresToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_RequiresToken_Call) Return(b bool) *MockTunnel_RequiresToken_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTunnel_RequiresToken_Call) RunAndReturn(run func() bool) *MockTunnel_RequiresToken_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Start(ctx context.Context, localAddr string) error {
	ret := _mock.Called(ctx, localAddr)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, localAddr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnel_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockTunnel_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - localAddr string
func (_e *MockTunnel_Expecter) Start(ctx any, localAddr any) *MockTunnel_Start_Call {
	return &MockTunnel_Start_Call{Call: _e.mock.On("Start", ctx, localAddr)}
}

func (_c *MockTunnel_Start_Call) Run(run func(ctx context.Context, localAddr string)) *MockTunnel_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnel_Start_Call) Return(err error) *MockTunnel_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnel_Start_Call) RunAndReturn(run func(ctx context.Context, localAddr string) error) *MockTunnel_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnel_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockTunnel_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTunnel_Expecter) Stop(ctx any) *MockTunnel_Stop_Call {
	return &MockTunnel_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockTunnel_Stop_Call) Run(run func(ctx context.Context)) *MockTunnel_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnel_Stop_Call) Return(err error) *MockTunnel_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnel_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *MockTunnel_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsCustomDomain provides a mock function for the type MockTunnel
func (_mock *MockTunnel) SupportsCustomDomain() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsCustomDomain")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTunnel_SupportsCustomDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsCustomDomain'
type MockTunnel_SupportsCustomDomain_Call struct {
	*mock.Call
}

// SupportsCustomDomain is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) SupportsCustomDomain() *MockTunnel_SupportsCustomDomain_Call {
	return &MockTunnel_SupportsCustomDomain_Call{Call: _e.mock.On("SupportsCustomDomain")}
}

func (_c *MockTunnel_SupportsCustomDomain_Call) Run(run func()) *MockTunnel_SupportsCustomDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_SupportsCustomDomain_Call) Return(b bool) *MockTunnel_SupportsCustomDomain_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTunnel_SupportsCustomDomain_Call) RunAndReturn(run func() bool) *MockTunnel_SupportsCustomDomain_Call {
	_c.Call.Return(run)
	return _c
}

// URL provides a mock function for the type MockTunnel
func (_mock *MockTunnel) URL() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for URL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnel_URL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URL'
type MockTunnel_URL_Call struct {
	*mock.Call
}

// URL is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) URL() *MockTunnel_URL_Call {
	return &MockTunnel_URL_Call{Call: _e.mock.On("URL")}
}

func (_c *MockTunnel_URL_Call) Run(run func()) *MockTunnel_URL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_URL_Call) Return(s string, err error) *MockTunnel_URL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTunnel_URL_Call) RunAndReturn(run func() (string, error)) *MockTunnel_URL_Call {
	_c.Call.Return(run)
	return _c
}
