// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTunnelCredentialStore creates a new instance of MockTunnelCredentialStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTunnelCredentialStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTunnelCredentialStore {
	mock := &MockTunnelCredentialStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTunnelCredentialStore is an autogenerated mock type for the TunnelCredentialStore type
type MockTunnelCredentialStore struct {
	mock.Mock
}

type MockTunnelCredentialStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTunnelCredentialStore) EXPECT() *MockTunnelCredentialStore_Expecter {
	return &MockTunnelCredentialStore_Expecter{mock: &_m.Mock}
}

// SetTunnelCredential provides a mock function for the type MockTunnelCredentialStore
func (_mock *MockTunnelCredentialStore) SetTunnelCredential(provider string, key string, value string) error {
	ret := _mock.Called(provider, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetTunnelCredential")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(provider, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnelCredentialStore_SetTunnelCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTunnelCredential'
type MockTunnelCredentialStore_SetTunnelCredential_Call struct {
	*mock.Call
}

// SetTunnelCredential is a helper method to define mock.On call
//   - provider string
//   - key string
//   - value string
func (_e *MockTunnelCredentialStore_Expecter) SetTunnelCredential(provider any, key any, value any) *MockTunnelCredentialStore_SetTunnelCredential_Call {
	return &MockTunnelCredentialStore_SetTunnelCredential_Call{Call: _e.mock.On("SetTunnelCredential", provider, key, value)}
}

func (_c *MockTunnelCredentialStore_SetTunnelCredential_Call) Run(run func(provider string, key string, value string)) *MockTunnelCredentialStore_SetTunnelCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTunnelCredentialStore_SetTunnelCredential_Call) Return(err error) *MockTunnelCredentialStore_SetTunnelCredential_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnelCredentialStore_SetTunnelCredential_Call) RunAndReturn(run func(provider string, key string, value string) error) *MockTunnelCredentialStore_SetTunnelCredential_Call {
	_c.Call.Return(run)
	return _c
}

// TunnelCredential provides a mock function for the type MockTunnelCredentialStore
func (_mock *MockTunnelCredentialStore) TunnelCredential(provider string, key string) string {
	ret := _mock.Called(provider, key)

	if len(ret) == 0 {
		panic("no return value specified for TunnelCredential")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(provider, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTunnelCredentialStore_TunnelCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TunnelCredential'
type MockTunnelCredentialStore_TunnelCredential_Call struct {
	*mock.Call
}

// TunnelCredential is a helper method to define mock.On call
//   - provider string
//   - key string
func (_e *MockTunnelCredentialStore_Expecter) TunnelCredential(provider any, key any) *MockTunnelCredentialStore_TunnelCredential_Call {
	return &MockTunnelCredentialStore_TunnelCredential_Call{Call: _e.mock.On("TunnelCredential", provider, key)}
}

func (_c *MockTunnelCredentialStore_TunnelCredential_Call) Run(run func(provider string, key string)) *MockTunnelCredentialStore_TunnelCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTunnelCredentialStore_TunnelCredential_Call) Return(s string) *MockTunnelCredentialStore_TunnelCredential_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTunnelCredentialStore_TunnelCredential_Call) RunAndReturn(run func(provider string, key string) string) *MockTunnelCredentialStore_TunnelCredential_Call {
	_c.Call.Return(run)
	return _c
}
